# -*- coding: utf-8 -*-
"""celsius_farenheit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3ukkSqSFsCLLl3oA-IEHMBNQmNn8z_P
"""

import tensorflow as tf
import numpy as np

celsius = np.array([-40, -10, 0, 8, 15, 22, 38], dtype=float)
fahrenheit = np.array([-40, 14, 32, 46, 59, 72, 100], dtype=float)

capa = tf.keras.layers.Dense(units=1, input_shape=[1])
modelo = tf.keras.Sequential([capa])

modelo.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

print("Comenzamos el entrenamiento del modelo...")
historial = modelo.fit(celsius, fahrenheit, epochs=1000, verbose=False)
print("Modelo entrenado y listo para hacer predicciones")

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de pérdida")
plt.plot(historial.history["loss"])

print("Hagamos una predicción! introduce un numero para transformarlo a fahrenheit: ")
cels_num = float(input(""))
resultado_calculado = (9/5)*cels_num+32
resultado_ia = modelo.predict(np.array([cels_num]))
print("El resultado del modelo es " + str(resultado_ia) + " fahrenheit y el resultado que calculamos con la formula matematica es " + str(resultado_calculado) + " fahrenheit")